const tickets = [
  // 🎵 Concerts
  {
    eventName: "Arijit Singh Live in Mumbai",
    eventDate: new Date("2025-12-15"),
    pricePerTicket: 2500,
    ticketsAvailable: 120,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Jio World Garden, Mumbai",
    eventCategory: "Concert",
    description: "Experience the magic of Arijit Singh's soulful voice live in concert.",
  },
  {
    eventName: "Coldplay – Music of the Spheres Tour",
    eventDate: new Date("2025-11-05"),
    pricePerTicket: 4500,
    ticketsAvailable: 250,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Bangalore Palace Grounds, Bengaluru",
    eventCategory: "Concert",
    description: "Coldplay returns to India with a spectacular light show and hit songs.",
  },
  {
    eventName: "Prateek Kuhad – Winter Tour",
    eventDate: new Date("2025-12-21"),
    pricePerTicket: 2100,
    ticketsAvailable: 150,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Phoenix Marketcity, Pune",
    eventCategory: "Concert",
    description: "Feel the warmth of Prateek Kuhad's melodies this winter.",
  },
  {
    eventName: "A.R. Rahman – Jai Ho World Tour",
    eventDate: new Date("2026-01-15"),
    pricePerTicket: 3500,
    ticketsAvailable: 300,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Nehru Stadium, Chennai",
    eventCategory: "Concert",
    description: "The maestro returns with a blend of classical and contemporary hits.",
  },
  {
    eventName: "Diljit Dosanjh Live",
    eventDate: new Date("2025-12-28"),
    pricePerTicket: 2800,
    ticketsAvailable: 200,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Punjab Cricket Stadium, Mohali",
    eventCategory: "Concert",
    description: "Punjabi music sensation bringing his energetic performance to the stage.",
  },
  {
    eventName: "Shreya Ghoshal – Soulful Melodies",
    eventDate: new Date("2026-02-14"),
    pricePerTicket: 2200,
    ticketsAvailable: 180,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Rabindra Sarobar Stadium, Kolkata",
    eventCategory: "Concert",
    description: "An evening of romantic Bollywood melodies by the queen of playback singing.",
  },

  // ⚽ Sports
  {
    eventName: "India vs Australia – ODI Match",
    eventDate: new Date("2025-12-02"),
    pricePerTicket: 1800,
    ticketsAvailable: 500,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Eden Gardens, Kolkata",
    eventCategory: "Sports",
    description: "Catch the thrilling clash between India and Australia live!",
  },
  {
    eventName: "ISL Semi-Final: Mumbai City FC vs Kerala Blasters",
    eventDate: new Date("2025-11-28"),
    pricePerTicket: 1200,
    ticketsAvailable: 350,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Mumbai Football Arena, Mumbai",
    eventCategory: "Sports",
    description: "A high-voltage ISL semi-final between two crowd favourites.",
  },
  {
    eventName: "India vs Pakistan – T20 Match",
    eventDate: new Date("2025-12-25"),
    pricePerTicket: 3000,
    ticketsAvailable: 700,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Wankhede Stadium, Mumbai",
    eventCategory: "Sports",
    description: "Witness the greatest cricket rivalry in the world!",
  },
  {
    eventName: "WWE India Live 2025",
    eventDate: new Date("2025-12-12"),
    pricePerTicket: 3500,
    ticketsAvailable: 900,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Indira Gandhi Indoor Stadium, Delhi",
    eventCategory: "Sports",
    description: "WWE superstars bring their power-packed action to India!",
  },
  {
    eventName: "IPL Final 2026",
    eventDate: new Date("2026-05-28"),
    pricePerTicket: 5000,
    ticketsAvailable: 1000,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Narendra Modi Stadium, Ahmedabad",
    eventCategory: "Sports",
    description: "The biggest cricket extravaganza finale at the world's largest stadium.",
  },
  {
    eventName: "Kabaddi World Cup – India vs Iran",
    eventDate: new Date("2026-03-20"),
    pricePerTicket: 800,
    ticketsAvailable: 450,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Thyagaraj Sports Complex, Delhi",
    eventCategory: "Sports",
    description: "Traditional Indian sport at its competitive best.",
  },
  {
    eventName: "Formula E – Hyderabad E-Prix",
    eventDate: new Date("2026-02-10"),
    pricePerTicket: 2500,
    ticketsAvailable: 600,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Street Circuit, Hyderabad",
    eventCategory: "Sports",
    description: "Electric racing comes to India with high-speed thrills.",
  },
  {
    eventName: "Chennai Open Tennis Championship",
    eventDate: new Date("2026-01-05"),
    pricePerTicket: 1500,
    ticketsAvailable: 300,
    owner: "69502d9406b0c82b0857bbdb",
    location: "SDAT Stadium, Chennai",
    eventCategory: "Sports",
    description: "Watch world-class tennis players compete in this ATP tournament.",
  },

  // 🎭 Theatre
  {
    eventName: "The Phantom of the Opera",
    eventDate: new Date("2025-11-20"),
    pricePerTicket: 2200,
    ticketsAvailable: 100,
    owner: "69502d9406b0c82b0857bbdb",
    location: "NCPA, Mumbai",
    eventCategory: "Theatre",
    description: "A timeless classic musical brought to life on the Indian stage.",
  },
  {
    eventName: "Macbeth – A Modern Adaptation",
    eventDate: new Date("2025-12-10"),
    pricePerTicket: 900,
    ticketsAvailable: 80,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Kamani Auditorium, Delhi",
    eventCategory: "Theatre",
    description: "A gripping modern retelling of Shakespeare's tragic masterpiece.",
  },
  {
    eventName: "Mamma Mia! The Musical",
    eventDate: new Date("2026-01-25"),
    pricePerTicket: 2500,
    ticketsAvailable: 150,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Jamshed Bhabha Theatre, Mumbai",
    eventCategory: "Theatre",
    description: "ABBA's greatest hits come alive in this feel-good musical.",
  },
  {
    eventName: "Tumhari Amrita – A Love Story",
    eventDate: new Date("2025-12-14"),
    pricePerTicket: 1200,
    ticketsAvailable: 120,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Prithvi Theatre, Mumbai",
    eventCategory: "Theatre",
    description: "A beautiful epistolary play spanning decades of love and longing.",
  },
  {
    eventName: "The Lion King – Stage Adaptation",
    eventDate: new Date("2026-03-15"),
    pricePerTicket: 3000,
    ticketsAvailable: 200,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Kingdom of Dreams, Gurugram",
    eventCategory: "Theatre",
    description: "Disney's beloved story with breathtaking costumes and puppetry.",
  },
  {
    eventName: "A Midsummer Night's Dream",
    eventDate: new Date("2025-11-10"),
    pricePerTicket: 800,
    ticketsAvailable: 90,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Ranga Shankara, Bengaluru",
    eventCategory: "Theatre",
    description: "Shakespeare's enchanting comedy set in a mystical forest.",
  },

  // 🎡 Festivals
  {
    eventName: "Sunburn Goa 2025",
    eventDate: new Date("2025-12-29"),
    pricePerTicket: 5500,
    ticketsAvailable: 1000,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Vagator Beach, Goa",
    eventCategory: "Festival",
    description: "Asia's biggest EDM festival with global artists and beach vibes.",
  },
  {
    eventName: "Jaipur Literature Festival 2025",
    eventDate: new Date("2025-01-24"),
    pricePerTicket: 400,
    ticketsAvailable: 800,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Diggi Palace, Jaipur",
    eventCategory: "Festival",
    description: "Celebrate books, authors, and conversations at the world's biggest lit fest.",
  },
  {
    eventName: "Lollapalooza India 2025",
    eventDate: new Date("2025-12-18"),
    pricePerTicket: 4900,
    ticketsAvailable: 950,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Mahalaxmi Race Course, Mumbai",
    eventCategory: "Festival",
    description: "Global artists and indie bands unite for two days of epic music.",
  },
  {
    eventName: "Rajasthan Folk Festival",
    eventDate: new Date("2025-10-30"),
    pricePerTicket: 1000,
    ticketsAvailable: 400,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Mehrangarh Fort, Jodhpur",
    eventCategory: "Festival",
    description: "Immerse yourself in the vibrant folk music and art of Rajasthan.",
  },
  {
    eventName: "Hornbill Festival 2025",
    eventDate: new Date("2025-12-01"),
    pricePerTicket: 600,
    ticketsAvailable: 500,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Naga Heritage Village, Kohima",
    eventCategory: "Festival",
    description: "Experience the rich culture and traditions of Nagaland's tribes.",
  },
  {
    eventName: "Goa Carnival 2026",
    eventDate: new Date("2026-02-21"),
    pricePerTicket: 350,
    ticketsAvailable: 1200,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Streets of Panaji, Goa",
    eventCategory: "Festival",
    description: "Vibrant parades, music, dance, and Goan culture at its finest.",
  },
  {
    eventName: "NH7 Weekender",
    eventDate: new Date("2025-11-15"),
    pricePerTicket: 3500,
    ticketsAvailable: 800,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Mahalaxmi Race Course, Pune",
    eventCategory: "Festival",
    description: "India's premier multi-genre music festival with indie and international acts.",
  },
  {
    eventName: "Pushkar Camel Fair",
    eventDate: new Date("2025-11-08"),
    pricePerTicket: 250,
    ticketsAvailable: 600,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Pushkar, Rajasthan",
    eventCategory: "Festival",
    description: "Traditional livestock fair with cultural performances and camel races.",
  },

  // 😂 Comedy
  {
    eventName: "Zakir Khan – Live Tour",
    eventDate: new Date("2025-11-22"),
    pricePerTicket: 1500,
    ticketsAvailable: 200,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Siri Fort Auditorium, Delhi",
    eventCategory: "Comedy",
    description: "Catch Zakir Khan's signature humor and storytelling live on stage.",
  },
  {
    eventName: "Kenny Sebastian – Professor of Tomfoolery",
    eventDate: new Date("2025-12-05"),
    pricePerTicket: 1300,
    ticketsAvailable: 180,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Good Shepherd Auditorium, Bengaluru",
    eventCategory: "Comedy",
    description: "A hilarious evening with Kenny Sebastian and his new stand-up special.",
  },
  {
    eventName: "Trevor Noah – Off the Record",
    eventDate: new Date("2025-12-01"),
    pricePerTicket: 2800,
    ticketsAvailable: 220,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Siri Fort Auditorium, Delhi",
    eventCategory: "Comedy",
    description: "Trevor Noah returns to India for his world comedy tour.",
  },
  {
    eventName: "Stand-Up for a Cause – Charity Night",
    eventDate: new Date("2025-11-30"),
    pricePerTicket: 800,
    ticketsAvailable: 250,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Kala Academy, Goa",
    eventCategory: "Comedy",
    description: "Top comedians come together for a special fundraising night.",
  },
  {
    eventName: "Vir Das – Landing Tour",
    eventDate: new Date("2026-01-18"),
    pricePerTicket: 2000,
    ticketsAvailable: 300,
    owner: "69502d9406b0c82b0857bbdb",
    location: "NCPA, Mumbai",
    eventCategory: "Comedy",
    description: "Emmy-nominated comedian brings his international success home.",
  },
  {
    eventName: "Biswa Kalyan Rath – Mood Kharab",
    eventDate: new Date("2025-12-22"),
    pricePerTicket: 1400,
    ticketsAvailable: 170,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Phoenix United, Lucknow",
    eventCategory: "Comedy",
    description: "Biswa's unique perspective on life's absurdities in his new special.",
  },
  {
    eventName: "Kapil Sharma Live",
    eventDate: new Date("2026-02-28"),
    pricePerTicket: 2500,
    ticketsAvailable: 400,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Thyagaraj Stadium, Delhi",
    eventCategory: "Comedy",
    description: "India's favorite comedian takes the stage with celebrity guests.",
  },
  {
    eventName: "Abhishek Upmanyu – Thoda Saaf Bol",
    eventDate: new Date("2025-11-26"),
    pricePerTicket: 1200,
    ticketsAvailable: 190,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Rangashankara, Bengaluru",
    eventCategory: "Comedy",
    description: "Relatable comedy about Indian life and millennial struggles.",
  },

  // 🎤 Other Events
  {
    eventName: "TechCrunch India Summit",
    eventDate: new Date("2025-12-08"),
    pricePerTicket: 2000,
    ticketsAvailable: 300,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Hyderabad Convention Centre, Hyderabad",
    eventCategory: "Other",
    description: "India's leading tech startup conference with global investors and founders.",
  },
  {
    eventName: "Food Fiesta – Delhi Street Food Carnival",
    eventDate: new Date("2025-11-18"),
    pricePerTicket: 500,
    ticketsAvailable: 600,
    owner: "69502d9406b0c82b0857bbdb",
    location: "India Gate Lawns, Delhi",
    eventCategory: "Other",
    description: "Taste the best of Indian street food at one grand event.",
  },
  {
    eventName: "The Great Indian Circus",
    eventDate: new Date("2025-11-17"),
    pricePerTicket: 700,
    ticketsAvailable: 400,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Chennai Trade Centre, Chennai",
    eventCategory: "Other",
    description: "A spectacular family-friendly circus filled with stunts and laughter.",
  },
  {
    eventName: "Comic Con India 2025",
    eventDate: new Date("2025-12-07"),
    pricePerTicket: 1200,
    ticketsAvailable: 1500,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Bombay Exhibition Centre, Mumbai",
    eventCategory: "Other",
    description: "Celebrate pop culture with cosplay, gaming, and celebrity panels.",
  },
  {
    eventName: "India Art Fair 2026",
    eventDate: new Date("2026-02-05"),
    pricePerTicket: 800,
    ticketsAvailable: 500,
    owner: "69502d9406b0c82b0857bbdb",
    location: "NSIC Grounds, Delhi",
    eventCategory: "Other",
    description: "South Asia's leading international art fair showcasing contemporary art.",
  },
  {
    eventName: "Auto Expo 2026",
    eventDate: new Date("2026-01-10"),
    pricePerTicket: 600,
    ticketsAvailable: 2000,
    owner: "69502d9406b0c82b0857bbdb",
    location: "India Expo Mart, Greater Noida",
    eventCategory: "Other",
    description: "Asia's largest automobile show with latest launches and concepts.",
  },
  {
    eventName: "Yoga Festival – Rishikesh",
    eventDate: new Date("2026-03-07"),
    pricePerTicket: 1500,
    ticketsAvailable: 350,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Parmarth Niketan, Rishikesh",
    eventCategory: "Other",
    description: "International yoga festival with masters from around the world.",
  },
  {
    eventName: "Bengaluru Poetry Festival",
    eventDate: new Date("2025-11-23"),
    pricePerTicket: 300,
    ticketsAvailable: 250,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Lahe Lahe, Bengaluru",
    eventCategory: "Other",
    description: "Celebrate spoken word, poetry, and storytelling with local and international poets.",
  },
  {
    eventName: "Wine & Jazz Festival",
    eventDate: new Date("2026-01-30"),
    pricePerTicket: 2200,
    ticketsAvailable: 400,
    owner: "69502d9406b0c82b0857bbdb",
    location: "Sula Vineyards, Nashik",
    eventCategory: "Other",
    description: "Premium wines paired with soulful jazz performances in a vineyard setting.",
  },
  {
    eventName: "Mumbai Marathon Expo",
    eventDate: new Date("2026-01-17"),
    pricePerTicket: 200,
    ticketsAvailable: 800,
    owner: "69502d9406b0c82b0857bbdb",
    location: "MMRDA Grounds, Mumbai",
    eventCategory: "Other",
    description: "Pre-marathon expo with fitness gear, nutrition advice, and running workshops.",
  },
];

module.exports = tickets;